name = "cupofluci-guestbook"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "cupofluci-guestbook"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
